"""initial schema

Revision ID: 6f7832725e27
Revises: 
Create Date: 2026-10-08 23:56:01.023961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f7832725e27'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False, comment='Start of the aggregation window'),
    sa.Column('window_end', sa.DateTime(), nullable=False, comment='End of the aggregation window'),
    sa.Column('period', sa.Enum('HOURLY', 'DAILY', 'WEEKLY', 'MONTHLY', name='metricperiod'), nullable=False),
    sa.Column('scope', sa.Enum('GLOBAL', 'MODEL', 'SEVERITY', 'ENTITY_TYPE', name='metricscope'), nullable=False),
    sa.Column('scope_value', sa.String(length=50), nullable=True, comment='Qualifier when scope is MODEL/SEVERITY/ENTITY_TYPE'),
    sa.Column('total_transactions', sa.Integer(), nullable=False),
    sa.Column('total_alerts', sa.Integer(), nullable=False),
    sa.Column('critical_alerts', sa.Integer(), nullable=False),
    sa.Column('high_alerts', sa.Integer(), nullable=False),
    sa.Column('medium_alerts', sa.Integer(), nullable=False),
    sa.Column('low_alerts', sa.Integer(), nullable=False),
    sa.Column('resolved_alerts', sa.Integer(), nullable=False),
    sa.Column('confirmed_frauds', sa.Integer(), nullable=False),
    sa.Column('false_positives', sa.Integer(), nullable=False),
    sa.Column('avg_risk_score', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('avg_resolution_time_sec', sa.Float(), nullable=True, comment='Average seconds from alert → resolution'),
    sa.Column('computed_at', sa.DateTime(), nullable=False, comment='When this snapshot was generated'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('window_start', 'period', 'scope', 'scope_value', name='uq_metrics_window_scope')
    )
    op.create_index('ix_metrics_scope', 'metrics_snapshots', ['scope', 'scope_value', 'window_start'], unique=False)
    op.create_index(op.f('ix_metrics_snapshots_window_start'), 'metrics_snapshots', ['window_start'], unique=False)
    op.create_index('ix_metrics_window', 'metrics_snapshots', ['window_start', 'period'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=50), nullable=False, comment='Business-facing transaction identifier'),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='Original event timestamp'),
    sa.Column('channel', sa.String(length=50), nullable=True, comment='Transaction channel (API, WEB, POS, ATM, etc.)'),
    sa.Column('entity_id', sa.String(length=100), nullable=False, comment='Originating entity (user/account/device ID)'),
    sa.Column('entity_type', sa.Enum('USER', 'ACCOUNT', 'TRANSACTION', 'DEVICE', name='entitytype'), nullable=False),
    sa.Column('source_account', sa.String(length=50), nullable=False),
    sa.Column('destination_account', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=100), nullable=True),
    sa.Column('geo_country', sa.String(length=3), nullable=True, comment='ISO 3166-1 alpha-2 country code'),
    sa.Column('geo_city', sa.String(length=100), nullable=True),
    sa.Column('geo_lat', sa.Float(), nullable=True),
    sa.Column('geo_lon', sa.Float(), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record ingestion time — never updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_destination_account'), 'transactions', ['destination_account'], unique=False)
    op.create_index(op.f('ix_transactions_entity_id'), 'transactions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_transactions_source_account'), 'transactions', ['source_account'], unique=False)
    op.create_index(op.f('ix_transactions_timestamp'), 'transactions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=True)
    op.create_index('ix_txn_amount_time', 'transactions', ['timestamp', 'amount'], unique=False)
    op.create_index('ix_txn_entity_time', 'transactions', ['entity_id', 'timestamp'], unique=False)
    op.create_index('ix_txn_source_dest', 'transactions', ['source_account', 'destination_account'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=20), nullable=False, comment='Business-facing alert ID, e.g. ALT-001'),
    sa.Column('entity', sa.String(length=100), nullable=False, comment='Entity display label (User #42521, Account #8839)'),
    sa.Column('entity_type', sa.Enum('USER', 'ACCOUNT', 'TRANSACTION', 'DEVICE', name='entitytype'), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False, comment='Composite risk score at detection time (0–100)'),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='alertseverity'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INVESTIGATING', 'RESOLVED', 'FALSE_POSITIVE', name='alertstatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transaction_id', sa.String(length=36), nullable=True, comment='Primary triggering transaction'),
    sa.Column('detection_run_id', sa.String(length=36), nullable=True, comment='Links to feature snapshots from the same run'),
    sa.Column('detection_time', sa.DateTime(), nullable=False, comment='Exact moment the detection engine flagged this'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Row insertion time'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last status mutation'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_detection_time', 'alerts', ['detection_time'], unique=False)
    op.create_index('ix_alert_entity_time', 'alerts', ['entity', 'detection_time'], unique=False)
    op.create_index('ix_alert_status_severity', 'alerts', ['status', 'severity'], unique=False)
    op.create_index(op.f('ix_alerts_alert_id'), 'alerts', ['alert_id'], unique=True)
    op.create_index(op.f('ix_alerts_detection_run_id'), 'alerts', ['detection_run_id'], unique=False)
    op.create_index(op.f('ix_alerts_entity'), 'alerts', ['entity'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_transaction_id'), 'alerts', ['transaction_id'], unique=False)
    op.create_table('feature_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('detection_run_id', sa.String(length=36), nullable=False, comment='Groups features belonging to the same detection run'),
    sa.Column('feature_name', sa.String(length=100), nullable=False, comment='Human-readable feature name, e.g. amount_zscore'),
    sa.Column('feature_value', sa.Float(), nullable=False),
    sa.Column('feature_category', sa.Enum('STATISTICAL', 'TEMPORAL', 'BEHAVIORAL', 'CONTEXTUAL', 'DEVICE', 'GEOGRAPHIC', name='featurecategory'), nullable=False),
    sa.Column('feature_description', sa.String(length=255), nullable=True, comment='Optional explanation of the feature'),
    sa.Column('model_version', sa.String(length=20), nullable=True, comment='Model version that produced / used this feature'),
    sa.Column('computed_at', sa.DateTime(), nullable=False, comment='When this feature was computed'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feat_name_cat', 'feature_snapshots', ['feature_name', 'feature_category'], unique=False)
    op.create_index('ix_feat_txn_run', 'feature_snapshots', ['transaction_id', 'detection_run_id'], unique=False)
    op.create_index(op.f('ix_feature_snapshots_detection_run_id'), 'feature_snapshots', ['detection_run_id'], unique=False)
    op.create_index(op.f('ix_feature_snapshots_transaction_id'), 'feature_snapshots', ['transaction_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('feedback_id', sa.String(length=20), nullable=False, comment='Business-facing feedback ID'),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.Enum('FRAUD', 'FALSE_POSITIVE', name='feedbackdecision'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True, comment='Analyst confidence (0–1)'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('analyst_id', sa.String(length=100), nullable=True),
    sa.Column('analyst_name', sa.String(length=200), nullable=True),
    sa.Column('used_for_training', sa.Boolean(), nullable=False, comment='Whether this signal has been consumed for retraining'),
    sa.Column('training_batch_id', sa.String(length=36), nullable=True, comment='ID of the training batch that used this'),
    sa.Column('resolved_at', sa.DateTime(), nullable=False, comment='When the analyst submitted the final label'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Row insertion time'),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_alert_id'), 'feedback', ['alert_id'], unique=True)
    op.create_index('ix_feedback_analyst', 'feedback', ['analyst_id', 'resolved_at'], unique=False)
    op.create_index(op.f('ix_feedback_analyst_id'), 'feedback', ['analyst_id'], unique=False)
    op.create_index('ix_feedback_decision_time', 'feedback', ['decision', 'resolved_at'], unique=False)
    op.create_index(op.f('ix_feedback_feedback_id'), 'feedback', ['feedback_id'], unique=True)
    op.create_index('ix_feedback_training', 'feedback', ['used_for_training'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.Enum('CREATED', 'STATUS_CHANGED', 'NOTE_ADDED', 'DECISION_SUBMITTED', 'REOPENED', 'ASSIGNED', name='investigationaction'), nullable=False, comment='Type of investigation action'),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=True, comment='FRAUD / LEGITIMATE / REVIEW (for DECISION_SUBMITTED)'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('analyst_id', sa.String(length=100), nullable=True),
    sa.Column('analyst_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When this action was recorded'),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inv_alert_time', 'investigations', ['alert_id', 'created_at'], unique=False)
    op.create_index('ix_inv_analyst_time', 'investigations', ['analyst_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_investigations_alert_id'), 'investigations', ['alert_id'], unique=False)
    op.create_index(op.f('ix_investigations_analyst_id'), 'investigations', ['analyst_id'], unique=False)
    op.create_index(op.f('ix_investigations_created_at'), 'investigations', ['created_at'], unique=False)
    op.create_table('model_score_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('detection_run_id', sa.String(length=36), nullable=True, comment='Same detection run as the alert & features'),
    sa.Column('model_name', sa.String(length=50), nullable=False, comment='e.g. statistical, behavioral, ml_ensemble'),
    sa.Column('model_version', sa.String(length=20), nullable=False, comment='Semantic version of the model'),
    sa.Column('raw_score', sa.Float(), nullable=False, comment='Unprocessed model output'),
    sa.Column('normalized_score', sa.Float(), nullable=False, comment='Score normalised to 0–100 scale'),
    sa.Column('confidence', sa.Float(), nullable=False, comment="Model's confidence in its score (0–1)"),
    sa.Column('weight', sa.Float(), nullable=False, comment='Weight used in composite scoring'),
    sa.Column('explanations', sa.Text(), nullable=True, comment='JSON array of explanation strings'),
    sa.Column('scored_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id', 'model_name', 'model_version', name='uq_score_per_model_version')
    )
    op.create_index(op.f('ix_model_score_records_alert_id'), 'model_score_records', ['alert_id'], unique=False)
    op.create_index(op.f('ix_model_score_records_detection_run_id'), 'model_score_records', ['detection_run_id'], unique=False)
    op.create_index('ix_score_alert_model', 'model_score_records', ['alert_id', 'model_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_score_alert_model', table_name='model_score_records')
    op.drop_index(op.f('ix_model_score_records_detection_run_id'), table_name='model_score_records')
    op.drop_index(op.f('ix_model_score_records_alert_id'), table_name='model_score_records')
    op.drop_table('model_score_records')
    op.drop_index(op.f('ix_investigations_created_at'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_analyst_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_alert_id'), table_name='investigations')
    op.drop_index('ix_inv_analyst_time', table_name='investigations')
    op.drop_index('ix_inv_alert_time', table_name='investigations')
    op.drop_table('investigations')
    op.drop_index('ix_feedback_training', table_name='feedback')
    op.drop_index(op.f('ix_feedback_feedback_id'), table_name='feedback')
    op.drop_index('ix_feedback_decision_time', table_name='feedback')
    op.drop_index(op.f('ix_feedback_analyst_id'), table_name='feedback')
    op.drop_index('ix_feedback_analyst', table_name='feedback')
    op.drop_index(op.f('ix_feedback_alert_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_feature_snapshots_transaction_id'), table_name='feature_snapshots')
    op.drop_index(op.f('ix_feature_snapshots_detection_run_id'), table_name='feature_snapshots')
    op.drop_index('ix_feat_txn_run', table_name='feature_snapshots')
    op.drop_index('ix_feat_name_cat', table_name='feature_snapshots')
    op.drop_table('feature_snapshots')
    op.drop_index(op.f('ix_alerts_transaction_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_entity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_detection_run_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_id'), table_name='alerts')
    op.drop_index('ix_alert_status_severity', table_name='alerts')
    op.drop_index('ix_alert_entity_time', table_name='alerts')
    op.drop_index('ix_alert_detection_time', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_txn_source_dest', table_name='transactions')
    op.drop_index('ix_txn_entity_time', table_name='transactions')
    op.drop_index('ix_txn_amount_time', table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_timestamp'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_source_account'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_entity_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_destination_account'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_metrics_window', table_name='metrics_snapshots')
    op.drop_index(op.f('ix_metrics_snapshots_window_start'), table_name='metrics_snapshots')
    op.drop_index('ix_metrics_scope', table_name='metrics_snapshots')
    op.drop_table('metrics_snapshots')
    # ### end Alembic commands ###

    # Drop PostgreSQL ENUM types explicitly. Autogenerate creates these types
    # implicitly when the tables are built, but does NOT drop them on
    # downgrade — leaving orphaned types that make a subsequent upgrade fail
    # with "type already exists". Dropping them here keeps the migration
    # fully reversible. (No-op on dialects without native ENUM types.)
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        for enum_name in (
            "metricperiod",
            "metricscope",
            "entitytype",
            "alertseverity",
            "alertstatus",
            "featurecategory",
            "feedbackdecision",
            "investigationaction",
        ):
            op.execute(f"DROP TYPE IF EXISTS {enum_name}")
